name: Continuous Integration

on:
  push:
    branches:
      - development

jobs:
  Deploy:
    name: Deploy for heroku...
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: install node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - name: eslint
        uses: icrawl/action-eslint@v1
      - name: Heroku deploy
        uses: akhileshns/heroku-deploy@v3.5.6
        with:
          heroku_api_key: ${{secrets.HEROKU_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_DEVELOPMENT}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}

