name: Continuous Deployment

on:
  pull_request:
    branches:
      - main

jobs:
  buildAndTest:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: install node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - name: eslint
        uses: icrawl/action-eslint@v1
