<<<<<<< HEAD
name: Continuous Integration - Deploy heroku
=======
name: Continuous Integration
>>>>>>> fa49bee30ebe2119e592e2fa79a185287b2515e0

on:
  pull_request:
    branches:
      - main

jobs:
  buildAndTest:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: install node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - name: eslint
        uses: icrawl/action-eslint@v1
      - name: Heroku deploy
<<<<<<< HEAD
        uses: akhileshns/heroku-deploy@v3.5.6
        with:
          heroku_api_key: ${{secrets.HEROKU_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP}}
=======
        uses: akhileshns/heroku-deploy@v3.5.7
        with:
          heroku_api_key: ${{secrets.HEROKU_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_DEVELOPMENT}}
>>>>>>> fa49bee30ebe2119e592e2fa79a185287b2515e0
          heroku_email: ${{secrets.HEROKU_EMAIL}}

